name: 3-D Contribution Graph (Default)

on:
  schedule:
    - cron: "0 18 * * *"   # daily at 18:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: GitHub-Profile-3D-Contrib
        uses: yoshi389111/github-profile-3d-contrib@v0.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push generated SVGs
        run: |
          git config user.name  "Mohsen"
          git config user.email "mr.marsxan@gmail.com"
          git add profile-3d-contrib/*.svg
          git commit -m "feat: update 3D graph default" || exit 0
          git push
